SocialGouv/dashlord-actions

report/src/summary/updownio.js, report/src/summary/updownio.test.js, report/www/src/components/UpdownIo.tsx, report/www/src/report.json, types/index.d.ts
=> refactor: move updownio grade into updownio-action

report/src/__snapshots__/generateUrlReport.test.js.snap, report/src/summary/codescan.js, report/src/summary/codescan.test.js, report/www/src/components/Codescan.tsx, report/www/src/components/Url.tsx, types/index.d.ts
=> refactor: move codescan grade into codescan-action

report/www/src/__tests__/__snapshots__/Dashboard.test.js.snap, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/Dashboard.tsx, report/www/src/components/Url.tsx
This makes badges clickables on the dashboard view and pointing to the related section in the Url view
=> feat: clickable badges

report/www/src/components/Codescan.tsx
=> fix(codescan): add table.rowKey

report/www/src/App.tsx, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/HTTP.tsx, report/www/src/components/Trackers.tsx, report/www/src/components/UpdownIo.tsx
fix an exception with UpDown and cosmetics
=> fix: small fixes

report/www/src/App.tsx, report/www/src/components/AppContainer.tsx, report/www/src/components/Dashboard.tsx, report/www/src/components/dashboard.cssmodule.scss
=> fix(report): dont limit dashboard table width

report/src/summary/__snapshots__/index.test.js.snap, report/src/summary/testssl.js, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/Dashboard.tsx, report/www/src/components/Grade.tsx, report/www/src/components/TestSSL.tsx, types/summary.d.ts
Add SSL expiration warning based on testssl report :
- added expireDate and expireSoon flag to url report summary
- added picto in dashboard
- added expiration information in detail page
warning is raised 30 days before expiration
=> feat(testssl): add expiration warning

report/www/src/components/HeaderSite.tsx, report/www/src/config.json, types/index.d.ts
Add a config.loginUrl that display a link to some other private dashlord
=> feat(report): add config.loginUrl

declaration-a11y/action.yml, declaration-a11y/index.js, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/__tests__/config.json, report/www/src/components/Dashboard.tsx, report/www/src/components/DeclarationA11y.tsx, report/www/src/components/Url.tsx, report/www/src/report.json, types/index.d.ts, types/summary.d.ts
- Correction wording
- Ajout du lien vers la declaration
=> feat(declaration-a11y): fix wording and detect declarationUrl

report/src/__snapshots__/generateUrlReport.test.js.snap, report/src/summary/__snapshots__/index.test.js.snap, report/src/summary/declaration-a11y.js, report/src/summary/declaration-a11y.test.js, report/www/src/__tests__/__snapshots__/Dashboard.test.js.snap, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/Dashboard.tsx, report/www/src/components/DeclarationA11y.tsx, report/www/src/components/columnHeader.cssmodule.scss
- better scoring
- better wording
=> feat: better a11y declaration reporting

report/www/pages/_app.tsx, report/www/pages/url/[...url].tsx, report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/Url.tsx, report/www/src/components/UrlHeader.tsx, report/www/src/components/UrlTabs.tsx
fix https://github.com/SocialGouv/dashlord/issues/41
=> fix(url): fix tabs navigation

report/www/src/components/FooterSite.tsx, report/www/src/components/HeaderSite.tsx
=> fix: config.marianne

.github/workflows/init-matrix.yml, .github/workflows/init.yml, .github/workflows/report.yml, .github/workflows/trivy.yml, report/src/generateUrlReport.js, report/src/summary/trivy.js, report/src/summary/trivy.test.js, report/www/src/components/Trivy.tsx, report/www/src/report.json, trivy/README.md, trivy/action.yml, types/index.d.ts
Allow trivy docker scans with a `config.url.docker` list of images
=> feat: trivy scans

report/www/src/components/Nuclei.tsx
=> fix(nuclei): fix report

report/www/src/__tests__/__snapshots__/Url.test.js.snap, report/www/src/components/Page.tsx, report/www/src/components/Url.tsx
=> fix(report): page alerts

report/www/src/__tests__/__snapshots__/Dashboard.test.js.snap, report/www/src/components/Dashboard.tsx
=> fix(report): simpler badge for rgpd and phase as first col

ecoindex/README.md, ecoindex/action.yml, report/src/__snapshots__/generateUrlReport.test.js.snap, report/src/generateUrlReport.js, report/src/summary/ecoindex.js, report/src/summary/index.js, report/www/src/__tests__/__snapshots__/Dashboard.test.js.snap, report/www/src/__tests__/__snapshots__/Intro.test.js.snap, report/www/src/components/Dashboard.tsx, report/www/src/components/EcoIndex.tsx, report/www/src/components/Intro.tsx, report/www/src/components/Url.tsx, report/www/src/components/badge.module.scss, report/www/src/config.json, report/www/src/report.json, types/index.d.ts, types/summary.d.ts
=> feat: add ecoindex action

report/src/summary/dependabot.js, report/src/summary/dependabot.test.js, report/www/src/components/Dependabot.tsx
Dismissed dependabot alerts :
- dont count in main dashboard
- dont show in details
=> fix(dependabot): dont count dismissed alerts

report/www/src/components/UrlHeader.tsx, report/www/src/config.json, types/index.d.ts
Allow to specify a `title` for a given url in dashlord.yaml
=> feat(report): add url.title if any

get-html/src/index.js
fix https://github.com/betagouv/dashlord/issues/152
=> fix(get-html): wait 5s before DOM snapshot

init/action.yml, init/dashlord.yml, init/src/__snapshots__/index.test.js.snap, init/src/index.js, init/src/index.test.js
Donne la possibilité de filter par "tags" lors l'init d'un scan
=> feat(init): add filter by tags
